# CPU контейнеров (только если есть лимит cgroup)
template: cgroup_cpu_warning
      on: cgroup.cpu_limit
  chart labels: cgroup_name=wordpress|nginx|mariadb|n8n*|postback*
    lookup: average -10m unaligned of used
      calc: $this
     units: %
     every: 2m
      warn: $this > 80
      crit: $this > 95
     delay: down 10m multiplier 1 max 1h
   summary: Контейнер ${label:cgroup_name} исчерпывает CPU
      info: ${label:cgroup_name} использует ${alarm_value}% CPU лимита
        to: telegram

# RAM контейнеров
template: cgroup_ram_warning
      on: cgroup.mem_usage
  chart labels: cgroup_name=wordpress|nginx|mariadb|n8n*|postback*
    lookup: average -5m unaligned of ram
      calc: $this
     units: MiB
     every: 1m
      warn: $this > 400
      crit: $this > 700
     delay: down 10m multiplier 1 max 1h
   summary: Контейнер ${label:cgroup_name} потребляет много RAM
      info: ${label:cgroup_name} использует ${alarm_value} MiB RAM
        to: telegram