# ══════════════════════════════════════════════
# Контейнер упал — wordpress
# ══════════════════════════════════════════════
alarm: container_wordpress_down
   on: docker_local.container_wordpress_state
lookup: max -60s unaligned of running
  calc: $this == 0 ? 1 : 0
 units: status
 every: 30s
  warn: $this > 0
 delay: down 2m multiplier 1 max 10m
summary: Контейнер wordpress упал
   info: Контейнер wordpress не запущен
     to: telegram

alarm: container_nginx_down
   on: docker_local.container_nginx_state
lookup: max -60s unaligned of running
  calc: $this == 0 ? 1 : 0
 units: status
 every: 30s
  warn: $this > 0
 delay: down 2m multiplier 1 max 10m
summary: Контейнер nginx упал
   info: Контейнер nginx не запущен
     to: telegram

alarm: container_mariadb_down
   on: docker_local.container_mariadb_state
lookup: max -60s unaligned of running
  calc: $this == 0 ? 1 : 0
 units: status
 every: 30s
  warn: $this > 0
 delay: down 2m multiplier 1 max 10m
summary: Контейнер mariadb упал
   info: Контейнер mariadb не запущен
     to: telegram

alarm: container_traefik_down
   on: docker_local.container_traefik_state
lookup: max -60s unaligned of running
  calc: $this == 0 ? 1 : 0
 units: status
 every: 30s
  warn: $this > 0
 delay: down 2m multiplier 1 max 10m
summary: Контейнер traefik упал
   info: Контейнер traefik не запущен
     to: telegram

alarm: container_redis_down
   on: docker_local.container_redis_state
lookup: max -60s unaligned of running
  calc: $this == 0 ? 1 : 0
 units: status
 every: 30s
  warn: $this > 0
 delay: down 2m multiplier 1 max 10m
summary: Контейнер redis упал
   info: Контейнер redis не запущен
     to: telegram

# ══════════════════════════════════════════════
# Healthcheck упал — wordpress
# ══════════════════════════════════════════════
alarm: container_wordpress_unhealthy
   on: docker_local.container_wordpress_health_status
lookup: max -60s unaligned of unhealthy
  calc: $this
 units: status
 every: 30s
  warn: $this > 0
 delay: down 5m multiplier 1 max 15m
summary: Healthcheck wordpress падает
   info: Healthcheck контейнера wordpress не проходит
     to: telegram

alarm: container_mariadb_unhealthy
   on: docker_local.container_mariadb_health_status
lookup: max -60s unaligned of unhealthy
  calc: $this
 units: status
 every: 30s
  warn: $this > 0
 delay: down 5m multiplier 1 max 15m
summary: Healthcheck mariadb падает
   info: Healthcheck контейнера mariadb не проходит
     to: telegram

alarm: container_nginx_unhealthy
   on: docker_local.container_nginx_health_status
lookup: max -60s unaligned of unhealthy
  calc: $this
 units: status
 every: 30s
  warn: $this > 0
 delay: down 5m multiplier 1 max 15m
summary: Healthcheck nginx падает
   info: Healthcheck контейнера nginx не проходит
     to: telegram